### ISSUE TITLE
GUI missing strings

### ISSUE THREAD

**Issue by yang-le** [jarikomppa/atanua#2]
![image](https://cloud.githubusercontent.com/assets/1812324/9085923/9c517af8-3bb3-11e5-926d-4abf28db6da4.png)
I compile your source code, and I open the program. I got above GUI, where were the strings? Any suggestion? Thank you.

**Comment by jarikomppa** [comment]
Looks like the font loading failed?

**Comment by yang-le** [comment]
oh, my mistake, now ok. Thanks again.
